# Generated by Django 2.0.2 on 2018-02-26 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_true', models.BooleanField(default=False)),
                ('alarm_off', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ДЕДЛАЙН',
                'verbose_name_plural': 'ДЕДЛАЙНы',
            },
        ),
        migrations.CreateModel(
            name='Comment_For_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.CharField(blank=True, max_length=256, null=True)),
                ('date_create', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Комментарий по проекту',
                'verbose_name_plural': 'Комментарии по проекту',
            },
        ),
        migrations.CreateModel(
            name='Data_Prime_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_yacor_project', models.CharField(blank=True, max_length=10, null=True)),
                ('date_create_project', models.DateField(auto_now=True)),
                ('date_start_project', models.DateField(blank=True, null=True)),
                ('date_deadline_project', models.DateField(blank=True, null=True)),
                ('date_fact_end', models.DateField(blank=True, null=True)),
                ('archiv_project', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Информаци по проекту',
                'verbose_name_plural': 'Информация по проектам',
            },
        ),
        migrations.CreateModel(
            name='File_For_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_file', models.CharField(blank=True, max_length=256, null=True)),
                ('boss_comment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Comment_For_Project')),
            ],
            options={
                'verbose_name': 'Прикрепленный файл к комментарию',
                'verbose_name_plural': 'Прикрепленные файлы к комментариям',
            },
        ),
        migrations.CreateModel(
            name='File_For_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_file', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Прикрепленный файл к проекту',
                'verbose_name_plural': 'Прикрепленные файлы к проекту',
            },
        ),
        migrations.CreateModel(
            name='Prime_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(blank=True, max_length=64, null=True)),
                ('description_project', models.CharField(blank=True, max_length=256, null=True)),
                ('who_create_project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Sub_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(blank=True, max_length=64, null=True)),
                ('description_project', models.CharField(blank=True, max_length=256, null=True)),
                ('prime_project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Prime_Project')),
                ('who_create_project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login')),
            ],
            options={
                'verbose_name': 'Субпроект',
                'verbose_name_plural': 'Субпроекты',
            },
        ),
        migrations.CreateModel(
            name='Sub_Project_Prime_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_yacor_project', models.CharField(blank=True, max_length=10, null=True)),
                ('level_project', models.IntegerField()),
                ('date_create_project', models.DateField(auto_now=True)),
                ('date_start_project', models.DateField(blank=True, null=True)),
                ('date_deadline_project', models.DateField(blank=True, null=True)),
                ('date_fact_end', models.DateField(blank=True, null=True)),
                ('local_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Sub_Project')),
                ('who_boss_project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login')),
            ],
            options={
                'verbose_name': 'Информация по субпроекту',
                'verbose_name_plural': 'Информация по субпроектам',
            },
        ),
        migrations.CreateModel(
            name='Sub_Project_Sub_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Sub_Project')),
                ('local_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Sub_Project_Prime_Data')),
            ],
            options={
                'verbose_name': 'Дополнительная информация по субпроекту',
                'verbose_name_plural': 'Дополнительная информация по субпроектам',
            },
        ),
        migrations.AddField(
            model_name='file_for_project',
            name='boss_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Sub_Project'),
        ),
        migrations.AddField(
            model_name='file_for_project',
            name='who_create',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login'),
        ),
        migrations.AddField(
            model_name='data_prime_project',
            name='prime_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Prime_Project'),
        ),
        migrations.AddField(
            model_name='data_prime_project',
            name='who_boss_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login'),
        ),
        migrations.AddField(
            model_name='comment_for_project',
            name='boss_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Sub_Project'),
        ),
        migrations.AddField(
            model_name='comment_for_project',
            name='who_create',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='boss_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Sub_Project'),
        ),
        migrations.AddField(
            model_name='alarm',
            name='prime_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Prime_Project'),
        ),
    ]
