# Generated by Django 2.0.2 on 2018-03-11 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('projects', '0003_auto_20180305_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_sub_project', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('date_create', models.DateField(auto_now=True)),
                ('date_update', models.DateField(blank=True, null=True)),
                ('sub_project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Sub_Project')),
                ('who_create', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
            },
        ),
        migrations.CreateModel(
            name='Outcom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_sub_project', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('date_create', models.DateField(auto_now=True)),
                ('date_update', models.DateField(blank=True, null=True)),
                ('sub_project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Sub_Project')),
                ('who_create', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
            },
        ),
    ]
