# Generated by Django 2.0.2 on 2018-03-12 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('projects', '0004_incom_outcom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incom_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Дополнительная информация о доходах',
                'verbose_name_plural': 'Дополнительная информация о доходах',
            },
        ),
        migrations.RemoveField(
            model_name='incom',
            name='date_update',
        ),
        migrations.AddField(
            model_name='incom',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='incom_data',
            name='local_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Incom'),
        ),
        migrations.AddField(
            model_name='incom_data',
            name='who_update',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login'),
        ),
    ]
