# Generated by Django 2.0.2 on 2018-03-14 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('projects', '0005_auto_20180312_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcom_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateField(blank=True, null=True)),
                ('local_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Outcom')),
                ('who_update', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login')),
            ],
            options={
                'verbose_name': 'Дополнительная информация о расходах',
                'verbose_name_plural': 'Дополнительная информация о расходах',
            },
        ),
    ]
