# Generated by Django 2.0.2 on 2018-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_outcom_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcom',
            name='date_update',
        ),
        migrations.AddField(
            model_name='outcom',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
