# Generated by Django 2.0.2 on 2018-03-16 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('projects', '0007_auto_20180314_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_For_Sub_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.CharField(blank=True, max_length=256, null=True)),
                ('date_create', models.DateField(auto_now=True)),
                ('boss_project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Sub_Project')),
                ('who_create', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login')),
            ],
            options={
                'verbose_name': 'Комментарий по подпроекту',
                'verbose_name_plural': 'Комментарии по подпроектам',
            },
        ),
        migrations.AlterModelOptions(
            name='comment_for_project',
            options={'verbose_name': 'Комментарий по проекту', 'verbose_name_plural': 'Комментарии по проектам'},
        ),
        migrations.AlterField(
            model_name='comment_for_project',
            name='boss_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Prime_Project'),
        ),
    ]
