# Generated by Django 2.0.2 on 2018-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20180316_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_for_comment',
            name='description_file',
        ),
        migrations.AddField(
            model_name='file_for_comment',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='file_atach_comment/'),
        ),
    ]
