# Generated by Django 2.0.2 on 2018-03-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180318_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_for_project',
            name='date_create',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file_for_project',
            name='boss_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Prime_Project'),
        ),
    ]
