# Generated by Django 2.0.2 on 2018-03-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20180318_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_for_project',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='file_atach_project/'),
        ),
    ]
