# Generated by Django 2.0.2 on 2018-03-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_file_for_project_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_company', models.CharField(blank=True, max_length=64, null=True)),
                ('location_company', models.CharField(blank=True, max_length=64, null=True)),
                ('site_company', models.CharField(blank=True, max_length=25, null=True)),
                ('mail_company', models.CharField(blank=True, max_length=25, null=True)),
                ('prime_project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Prime_Project')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
        migrations.CreateModel(
            name='Data_Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_client', models.CharField(blank=True, max_length=64, null=True)),
                ('doljnost', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_client', models.CharField(blank=True, max_length=25, null=True)),
                ('mail_client', models.CharField(blank=True, max_length=25, null=True)),
                ('local_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Contacts')),
            ],
            options={
                'verbose_name': 'Дополнительная информация к контактным данным',
                'verbose_name_plural': 'Дополнительная информация к контактным данным',
            },
        ),
    ]
