# Generated by Django 2.0.2 on 2018-03-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_contacts_data_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='mail_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='site_company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data_contacts',
            name='doljnost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data_contacts',
            name='mail_client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='data_contacts',
            name='phone_client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
