# Generated by Django 2.0.2 on 2018-03-25 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('projects', '0013_auto_20180321_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_start_status', models.DateField(auto_now=True)),
                ('date_deadline_status', models.DateField(blank=True, null=True)),
                ('date_fact_end_status', models.DateField(blank=True, null=True)),
                ('status_1', models.BooleanField(default=False)),
                ('status_2', models.BooleanField(default=False)),
                ('status_3', models.BooleanField(default=False)),
                ('status_4', models.BooleanField(default=False)),
                ('status_5', models.BooleanField(default=False)),
                ('status_6', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Статус данные',
                'verbose_name_plural': 'Статусы данные',
            },
        ),
        migrations.AddField(
            model_name='comment_for_project',
            name='status_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment_for_project',
            name='status_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment_for_project',
            name='status_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment_for_project',
            name='status_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment_for_project',
            name='status_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment_for_project',
            name='status_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prime_project',
            name='status_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prime_project',
            name='status_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prime_project',
            name='status_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prime_project',
            name='status_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prime_project',
            name='status_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prime_project',
            name='status_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_project',
            name='status_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_project',
            name='status_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_project',
            name='status_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_project',
            name='status_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_project',
            name='status_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sub_project',
            name='status_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='status_project',
            name='boss_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Prime_Project'),
        ),
        migrations.AddField(
            model_name='status_project',
            name='who_resend_status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login'),
        ),
    ]
