# Generated by Django 2.0.2 on 2018-03-27 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20180326_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incom',
            name='sub_project',
        ),
        migrations.AddField(
            model_name='incom',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Prime_Project'),
        ),
        migrations.AddField(
            model_name='incom',
            name='status_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incom',
            name='status_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incom',
            name='status_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incom',
            name='status_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incom',
            name='status_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incom',
            name='status_6',
            field=models.BooleanField(default=False),
        ),
    ]
