# Generated by Django 2.0.2 on 2018-03-27 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20180327_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incom',
            old_name='inc_sub_project',
            new_name='inc_project',
        ),
    ]
