# Generated by Django 2.0.2 on 2018-03-27 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20180327_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcom',
            name='sub_project',
        ),
        migrations.AddField(
            model_name='outcom',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Prime_Project'),
        ),
        migrations.AddField(
            model_name='outcom',
            name='status_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outcom',
            name='status_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outcom',
            name='status_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outcom',
            name='status_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outcom',
            name='status_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outcom',
            name='status_6',
            field=models.BooleanField(default=False),
        ),
    ]
