# Generated by Django 2.0.2 on 2018-03-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20180327_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outcom',
            old_name='inc_sub_project',
            new_name='inc_project',
        ),
    ]
