# Generated by Django 2.0.2 on 2018-03-28 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('projects', '0018_auto_20180327_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Incom_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='file_atach_project_incom/')),
                ('description_file', models.CharField(blank=True, max_length=256, null=True)),
                ('date_create', models.DateField(auto_now=True)),
                ('local_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Incom_Data')),
                ('who_create', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User_Login')),
            ],
            options={
                'verbose_name': 'Прикрепленный файл к доходу',
                'verbose_name_plural': 'Прикрепленные файлы к доходам',
            },
        ),
    ]
