# Generated by Django 2.0.2 on 2018-04-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_file_outcom_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_project',
            name='do_it',
            field=models.BooleanField(default=False),
        ),
    ]
